const data = [
    {
        name:"Anthony Davis",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.5,
            averageTwopoints:4.35,
            averageThreepoints:3.8,
            averageTeam_player:3.05,
            averageAtheleticism:4.1,
            averageDefense:4.25,
            averageRebounds:4.2,
            averageBlocks:3,//fixme 
        }
    }, 
    {
        name:"Draymond Green",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.2,
            averageTwopoints:3.3,
            averageThreepoints:3.45,
            averageTeam_player:3.65,
            averageAtheleticism:3.9,
            averageDefense:4.25,
            averageRebounds:3.15,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Giannis Antetokounmpo",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.5,
            averageTwopoints:3.75,
            averageThreepoints:3.35,
            averageTeam_player:3.75,
            averageAtheleticism:4.05,
            averageDefense:4.2,
            averageRebounds:3.9,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Rudy Gobert",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.3,
            averageTwopoints:3.35,
            averageThreepoints:2.65,
            averageTeam_player:1.55,
            averageAtheleticism:3.2,
            averageDefense:4.2,
            averageRebounds:4.35,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Marcus Smart",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4,
            averageTwopoints:2.8,
            averageThreepoints:3.4,
            averageTeam_player:3.3,
            averageAtheleticism:3.65,
            averageDefense:4.2,
            averageRebounds:1.9,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Chris Paul",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.15,
            averageTwopoints:3.35,
            averageThreepoints:3.95,
            averageTeam_player:4,
            averageAtheleticism:3.65,
            averageDefense:4.15,
            averageRebounds:2.3,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Andre Roberson",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:3.75,
            averageTwopoints:2.7,
            averageThreepoints:2.5,
            averageTeam_player:2.9,
            averageAtheleticism:3.4,
            averageDefense:4.15,
            averageRebounds:2.75,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Kawhi Leonard",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.5,
            averageTwopoints:3.7,
            averageThreepoints:3.85,
            averageTeam_player:3.35,
            averageAtheleticism:3.7,
            averageDefense:4.1,
            averageRebounds:2.75,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Paul George",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.5,
            averageTwopoints:3.3,
            averageThreepoints:3.8,
            averageTeam_player:3.75,
            averageAtheleticism:3.7,
            averageDefense:4.1,
            averageRebounds:2.9,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Klay Thompson",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.35,
            averageTwopoints:3.9,
            averageThreepoints:4.3,
            averageTeam_player:3.15,
            averageAtheleticism:3.55,
            averageDefense:4.1,
            averageRebounds:2.1,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Victor Oladipo",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.25,
            averageTwopoints:3.1,
            averageThreepoints:3.8,
            averageTeam_player:3.45,
            averageAtheleticism:3.75,
            averageDefense:4.1,
            averageRebounds:2.55,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Al Horford",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.15,
            averageTwopoints:4.1,
            averageThreepoints:4.2,
            averageTeam_player:3.05,
            averageAtheleticism:3.6,
            averageDefense:4.1,
            averageRebounds:3.2,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Joel Embiid",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.4,
            averageTwopoints:4.2,
            averageThreepoints:3.65,
            averageTeam_player:2.55,
            averageAtheleticism:3.9,
            averageDefense:4.05,
            averageRebounds:4.1,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Eric Bledsoe",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.15,
            averageTwopoints:3,
            averageThreepoints:3.5,
            averageTeam_player:3.9,
            averageAtheleticism:4,
            averageDefense:4.05,
            averageRebounds:2.25,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Jimmy Butler",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.3,
            averageTwopoints:3.3,
            averageThreepoints:3.55,
            averageTeam_player:3.4,
            averageAtheleticism:3.7,
            averageDefense:4,
            averageRebounds:2.3,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Jrue Holiday",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.2,
            averageTwopoints:3.45,
            averageThreepoints:3.7,
            averageTeam_player:3.7,
            averageAtheleticism:3.75,
            averageDefense:4,
            averageRebounds:2.15,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Kyle Lowry",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.15,
            averageTwopoints:3.5,
            averageThreepoints:3.85,
            averageTeam_player:4.05,
            averageAtheleticism:4.15,
            averageDefense:4,
            averageRebounds:2.4,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Dejounte Murray",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:3.8,
            averageTwopoints:3.2,
            averageThreepoints:3.35,
            averageTeam_player:3.6,
            averageAtheleticism:3.6,
            averageDefense:4,
            averageRebounds:3.4,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"LeBron James",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.5,
            averageTwopoints:3.95,
            averageThreepoints:3.75,
            averageTeam_player:4,
            averageAtheleticism:4.1,
            averageDefense:3.95,
            averageRebounds:2.95,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Russell Westbrook",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4.35,
            averageTwopoints:3.5,
            averageThreepoints:3.55,
            averageTeam_player:4.15,
            averageAtheleticism:4.35,
            averageDefense:3.95,
            averageRebounds:3.6,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Marc Gasol",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4,
            averageTwopoints:4.15,
            averageThreepoints:3.85,
            averageTeam_player:2.8,
            averageAtheleticism:3.1,
            averageDefense:3.95,
            averageRebounds:3.5,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Myles Turner",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4,
            averageTwopoints:3.85,
            averageThreepoints:4,
            averageTeam_player:1.65,
            averageAtheleticism:3.25,
            averageDefense:3.95,
            averageRebounds:3.5,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Steven Adams",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:4,
            averageTwopoints:3.45,
            averageThreepoints:2.65,
            averageTeam_player:1.65,
            averageAtheleticism:3.25,
            averageDefense:3.95,
            averageRebounds:3.3,
            averageBlocks:3,//fixme 
        }
    },
    {
        name:"Patrick Beverley",
        beginner:false,
        heigth:178,//fixme
        weigth:78,//fixme
        averageRatings:{
            averageOverall_score:3.9,
            averageTwopoints:2.95,
            averageThreepoints:3.05,
            averageTeam_player:3.5,
            averageAtheleticism:3.9,
            averageDefense:3.95,
            averageRebounds:2.7,
            averageBlocks:3,//fixme 
        }
    },

]